model_list:
  - model_name: gpt-5
    litellm_params:
      model: gpt-5
      api_base: os.environ/LLM_BACKEND_API_BASE
      api_key: os.environ/LLM_BACKEND_API_KEY

litellm_settings:
  drop_params: True
